frontend/package-lock.json
frontend/package.json
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/Sidebar/index.ts
frontend/src/components/Topbar/Topbar.tsx
frontend/src/components/Topbar/index.ts
frontend/src/components/UsersList/UsersList.tsx
frontend/src/components/UsersList/index.ts
frontend/src/lib/parseJwt.ts
frontend/src/pages/main/main.tsx
frontend/src/pages/signin/signin.tsx

Tutaj są:
- WN2-20
- WN2-21
- WN2-22
- WN2-17

WN2-13: Możliwość wyświetlania wiadomości

---

frontend/src/components/Message/Message.tsx

add ability to edit messages from channels other than `main`

WN2-43 Możliwość edycji wiadomości na innych kanałach

---

frontend/src/components/Message/Message.tsx

add ability to delete messages

WN2-42 Zaimplementuj możliwość usuwania wiadomości

---

frontend/public/locales/de/sidebar.json
frontend/public/locales/en/sidebar.json
frontend/public/locales/pl/sidebar.json
frontend/src/components/Sidebar/Sidebar.tsx

Added translations for the `Sidebar`

WN2-33 Dodaj tłumaczenia dla komponentu `Sidebar`

---

frontend/public/locales/de/userslist.json
frontend/public/locales/en/userslist.json
frontend/public/locales/pl/userslist.json
frontend/src/components/UsersList/UsersList.tsx

added translations for the `UsersList`

WN2-34 Dodaj tłumaczenia dla komponentu `UsersList`

---

frontend/public/locales/de/signin.json
frontend/public/locales/en/signin.json
frontend/public/locales/pl/signin.json
frontend/src/pages/signin/signin.tsx

added translations to `signin`

WN2-36 Dodaj tłumaczenia dla strony `signin`

---

frontend/public/locales/de/dashboard.json
frontend/public/locales/en/dashboard.json
frontend/public/locales/pl/dashboard.json
frontend/src/pages/dashboard/dashboard.tsx

add translations for `dashboard`

WN2-35 Dodaj tłumaczenia dla strony `dashboard`

---

frontend/public/locales/de/edit.json
frontend/public/locales/en/edit.json
frontend/public/locales/pl/edit.json
frontend/src/pages/edit/edit.tsx

WN2-38 Dodaj tłumaczenia dla strony `edit`

---

frontend/src/components/UserDetails/UserDetails.tsx

Implement fetching of user's details

WN2-51 Zaimplementuj pobieranie danych które użytkownik chce, by wyświetlać dla innych

---

frontend/src/components/ChatCreate/ChatCreate.tsx
frontend/src/components/ChatCreate/index.ts
frontend/src/components/Sidebar/Sidebar.tsx

WN2-57 Dodaj możliwość tworzenia czatów prywatnych

---

frontend/src/components/Message/Message.tsx

add verification for message deletion

WN2-64 Podwójna weryfikacja usuwania wiadomości

---

frontend/src/components/Message/Message.tsx

Add ability to cancel editing of a message

WN2-65 Anulowanie edycji wiadomości

---

frontend/src/components/Message/Message.tsx

WN2-69-napraw-message-component

---

frontend/public/locales/de/signin.json
frontend/public/locales/en/signin.json
frontend/public/locales/pl/signin.json
frontend/src/pages/signin/signin.tsx

WN2-67 Dodaj stan ładowania do formularza logującego

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/UsersList/UsersList.tsx
frontend/src/pages/signin/signin.tsx

- added logout button to sidebar

[WIP] WN2-47: Implementacja wyświetlania statusu użytkownika

---

frontend/src/components/Sidebar/Sidebar.tsx

Add missing import to `Sidebar`

WN2-88 Dodaj brakujący import do komponentu `Sidebar`

---

frontend/src/components/Sidebar/Chat/Chat.tsx
frontend/src/components/Sidebar/Chat/index.ts
frontend/src/components/Sidebar/Sidebar.tsx

added notifications to sidebar

WN2-74 Dodaj powiadomienia w Sidebarze

---

frontend/src/components/UsersList/UsersList.tsx

Add missing `AvatarBadge` import to `UsersList`

WN2-89 Dodaj brakujący import komponentu `AvatarBadge` do komponentu `UsersList`

---

frontend/src/components/MemberAdd/MemberAdd.tsx
frontend/src/components/MemberManage/MemberManage.tsx
frontend/src/components/UsersList/UsersList.tsx

added necessery functionalities for effective management of channel's members

WN2-80 Dodaj funkcjonalność zarządzania uprawnieniami do kanałów

---

frontend/src/components/Sidebar/Sidebar.tsx

Fetch data after the channel creation popup gets closed

WN2-84 Po kliknięciu `add-group-chat` nie widać nowego czatu do momentu odświeżenia strony

---

frontend/src/pages/signin/signin.tsx

WN2-47: remove commented out code

---

frontend/public/locales/de/signin.json
frontend/public/locales/en/signin.json
frontend/public/locales/pl/signin.json
frontend/src/pages/signin/signin.tsx

add translations for error message

WN2-81 Strona logowania rozbieżność w domyślnym języku

---

frontend/public/locales/de/register.json
frontend/public/locales/en/register.json
frontend/public/locales/pl/register.json
frontend/src/pages/register/register.tsx

Add missing translations to `register`

WN2-86 Formularz rejestracji ujednolicenie domyślnego języka

---

frontend/src/components/Sidebar/Sidebar.tsx

Fixed a bug where the fetching of the channels removes the main channel

WN2-91 Po aktualizacji kanałów w Sidebarze znika kanał `main`

---

frontend/src/components/LanguageSelector/LanguageSelector.tsx
frontend/src/components/LanguageSelector/index.ts

Create `LanguageSelector` component

WN2-94 Stwórz komponent do zmiany języka

---

frontend/src/pages/signin/signin.tsx

Add `LanguageSelector` to `signin`

WN2-95 Zaimplementuj `LanguageSelector` do strony logowania

---

frontend/src/pages/register/register.tsx

- removed error logging in the console,
- added a chakra alert box to log exceptions,
- added a chakra alert box to show that you have succesfully registered.

WN2-68: register form adjustment

---

frontend/src/pages/register/register.tsx

Add `LanguageSelector` to `register`

WN2-96 Zaimplementuj `LanguageSelector` do strony rejestracji

---

frontend/src/components/MemberAdd/MemberAdd.tsx
frontend/src/components/MemberManage/MemberManage.tsx
frontend/src/components/Message/Message.tsx
frontend/src/components/Sidebar/Chat/Chat.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/UserDetails/UserDetails.tsx
frontend/src/components/UsersList/UsersList.tsx
frontend/src/pages/dashboard/dashboard.tsx
frontend/src/pages/edit/edit.tsx
frontend/src/pages/register/register.tsx

- formatted code to fix eslint warnings

WN2-90: eslint warnings

---

frontend/src/components/MemberManage/MemberManage.tsx
frontend/src/components/UsersList/UsersList.tsx

WN2-87 Po kliknięciu w użytkownika w Members ma się wyświetlić info o nim

---

frontend/src/components/Sidebar/Sidebar.tsx

Add periodic fetching of channels to `Sidebar`

WN2-97 Dodaj odświeżanie do listy czatów w Sidebarze

---

frontend/src/components/Sidebar/Sidebar.tsx

- remove notifications button
- make settings button actually work lol

WN2-98 Dopracuj `sidebar`

---

frontend/src/pages/dashboard/dashboard.tsx

remove `Topbar` from `dashboard`

WN2-99 Usuń `Topbar`

---

frontend/src/components/UsersList/User/User.tsx
frontend/src/components/UsersList/User/index.ts
frontend/src/components/UsersList/UsersList.tsx

add periodic check for user's status

WN2-100 Status użytkownika nie jest aktualizowany w `UsersList`

---

frontend/src/components/MemberManage/MemberManage.tsx
frontend/src/components/Message/Message.tsx
frontend/src/components/UserDetails/UserDetails.tsx
frontend/src/components/UsersList/User/User.tsx
frontend/src/components/UsersList/UsersList.tsx

The data of currently logged in user is always displayed

WN2-101 Zawsze wyświetlaj dane obecnie zalogowanego użytkownika

---

frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/pages/dashboard/dashboard.tsx

WN2-102: fixed logout

---

frontend/src/components/ChatCreate/ChatCreate.tsx
frontend/src/components/MemberAdd/MemberAdd.tsx
frontend/src/components/MemberManage/MemberManage.tsx
frontend/src/components/Message/Message.tsx
frontend/src/components/Sidebar/Chat/Chat.tsx
frontend/src/components/Sidebar/Sidebar.tsx
frontend/src/components/UserDetails/UserDetails.tsx
frontend/src/components/UsersList/User/User.tsx
frontend/src/components/UsersList/UsersList.tsx
frontend/src/lib/axios.ts
frontend/src/pages/dashboard/dashboard.tsx
frontend/src/pages/edit/edit.tsx
frontend/src/pages/signin/signin.tsx

Move `Authorization` header to `axiosInstance`

WN2-105 Dodaj `Authorization` header do `AxiosInstance`

---

frontend/src/pages/edit/edit.tsx

WN2-104 Upodobnij formularz edycji do formularza logowania
